# -*- coding: utf-8 -*-
"""HA#3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMGjccP7IgRdp-thdkYJXMoB_8jnA6HA
"""

import threading
import time

def thread_a():
    lock_a.acquire()
    time.sleep(2)

    lock_b.acquire()
    time.sleep(2)

    lock_a.release()
    lock_b.release()

def thread_b():

    lock_b.acquire()
    time.sleep(5)

    lock_a.acquire()
    time.sleep(5)

    lock_b.release()
    lock_a.release()
lock_a = threading.Lock()
lock_b = threading.Lock()

thread1 = threading.Thread(target=thread_a)
thread2 = threading.Thread(target=thread_b)

thread1.start()
thread2.start()

thread1.join()
thread2.join()
print('Finished.')